version: '3.9'

networks:
  fcgi_network:
    external: true



services: 
  hello: 
    image: hello06:local
    build: ./hello/
    volumes:
      - ./hello/:/etc/nginx/
    container_name: hello_serv
    networks:
      fcgi_network:
        ipv4_address: 172.20.0.2
    

  nginx: 
    image: nginx:latest
    build: ./nginx/
    volumes:
      - ./nginx/:/etc/nginx/
    container_name: nginx_serv
    networks:
      fcgi_network:
        ipv4_address: 172.20.0.3
    ports: 
      - "80:8080"
    


    
  